### ISSUE TITLE
Organizational relationships

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis-ontology#138] opened 2015-08-25 16:51 UTC
Hi everyone,
  Currently we don't have a structured way through which to associate one organization to another.  For instance, let's take a look at:
https://data.globalchange.gov/organization/university-wisconsin-milwaukee.thtml

We would like to affirm that the University of Wisconsin-Milwaukee is a branch of the University of Wisconsin System.  In this example, we have captured the "University of Wisconsin (system)" component, but not the "branch of."

The "branch of" association can be found at:
https://data.globalchange.gov/organization/university-wisconsin-milwaukee.thtml

Would this require the addition of terms such as "branch of," "office of," "affiliated with," etc. in our ontology or is there a way around this?  I am thinking of the use case of someone wanting to see all of the contributions of the University of Wisconsin system to the NCA3.  This would include:
- all academic departments of the system's branches (e.g. https://data.globalchange.gov/organization/university-wisconsin-department-rural-sociology)
- campuses making up the system:
  https://data.globalchange.gov/organization/university-wisconsin-madison

Would we need to add the "branch of," "department of" terms to our ontology in order to facilitate the writing of this SPARQL query?

**Comment by rewolfe** [comment] 2015-08-25 17:14
@justgo129 - issue #137 and this issue appear to be the same.

On Tue, Aug 25, 2015 at 12:51 PM, justgo129 notifications@github.com
wrote:

> Hi everyone,
> Currently we don't have a structured way through which to associate one
> organization to another. For instance, let's take a look at:
> 
> https://data.globalchange.gov/organization/university-wisconsin-milwaukee.thtml
> 
> We would like to affirm that the University of Wisconsin-Milwaukee is a
> branch of the University of Wisconsin System. In this example, we have
> captured the "University of Wisconsin (system)" component, but not the
> "branch of."
> 
> The "branch of" association can be found at:
> 
> https://data.globalchange.gov/organization/university-wisconsin-milwaukee.thtml
> 
> Would this require the addition of terms such as "branch of," "office of,"
> "affiliated with," etc. in our ontology or is there a way around this? I am
> thinking of the use case of someone wanting to see all of the contributions
> of the University of Wisconsin system to the NCA3. This would include:
> - all academic departments of the system's branches (e.g.
>   https://data.globalchange.gov/organization/university-wisconsin-department-rural-sociology
>   )
> - campuses making up the system:
>   https://data.globalchange.gov/organization/university-wisconsin-madison
> 
> Would we need to add the "branch of," "department of" terms to our
> ontology in order to facilitate the writing of this SPARQL query?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/issues/138.

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by zednis** [comment] 2015-08-25 17:18
I am closing this issue as a duplicate of #137

**Closed as completed by zednis** 2015-08-25 17:18 UTC
Labels: duplicate

**Comment by justgo129** [comment] 2015-08-25 18:35
dang, that was definitely inadvertent.  Apologies.
