### ISSUE TITLE
GCIS Ontology Version

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis-ontology#149] opened 2015-09-08 17:26 UTC
Continuation of https://github.com/USGCRP/gcis-ontology/pull/54

**Comment by zednis** [comment] 2015-09-08 20:06
duplicate of #148?

**Comment by justgo129** [comment] 2015-09-10 00:54
Good catch, I wonder why this keeps happening.  I just closed #148; let's work with #149 (this one).

**Comment by justgo129** [comment] 2015-09-21 21:27
@zednis @rewolfe I'd like to discuss this further (even offline) upon your return from PTO.  Thanks.

**Comment by zednis** [comment] 2015-09-21 21:39
:+1: I will be back to normal work on the 28th (Monday)

**Comment by rewolfe** [comment] 2015-09-22 14:01
I will be back in the office Oct. 5.

On Mon, Sep 21, 2015 at 5:39 PM, Stephan Zednik notifications@github.com
wrote:

> [image: :+1:] I will be back to normal work on the 28th (Monday)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGCRP/gcis-ontology/issues/149#issuecomment-142117063
> .

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by justgo129** [comment] 2015-09-22 14:26
Sounds good.  Tabled #149 until the week of October 5.

**Comment by justgo129** [comment] 2015-10-20 18:16
October update: @zednis is looking into this issue and will report back.

**Comment by justgo129** [comment] 2015-10-27 20:37
Per today's discussion, we will name the updated version GCIS 2.0 upon the closure of the github issues.

**Comment by zednis** [comment] 2015-11-03 18:11
What do we want the `owl:versionIRI` to be?

Options:
- http://data.globalchange.gov/gcis-2.0.owl
- http://data.globalchange.gov/gcis-2.0
- http://data.globalchange.gov/2.0/gcis.owl
- http://data.globalchange.gov/2.0/gcis

1) This should be a resolvable URL where we will make the 2.0 version of the ontology available
2) My preference is to leave the .owl off the URI
3) We should have HTML documentation for this specific version available at the URI using content negotiation - which is why I have my preference stated in (2)

**Comment by zednis** [comment] 2015-11-03 18:22
Do we want to add a `owl:versionIRI` for version 1.2?

**Comment by zednis** [comment] 2015-11-03 18:23
Additional note, when we decide on version 2.0 we should create a release of the ontology in github

**Closed as completed** 2015-11-09 15:59 UTC
